export const COLORS = {
  Black: 'black',
  White: 'white',
  Red: 'red',
  Green: 'green',
  Yellow: 'yellow',
  Blue: 'blue',
  Grey: 'grey',
  BorderColor: '#C5C5C5',
  ThemeColor: '#ffb605',
  LightYellow: '#fff9eb',
  LightGreen: '#55ad52',
  LightGrey: '#999',
  IconTintColor: '#A0A0A0',
  LightBorderColor: '#D5D5D5',
  ProductBGColor: '#e0dede',
  DarkGrey: '#767577',
  Transparent: 'rgba(0, 0, 0, 0.5)',
  ExtraLightGreen: '#34c759',
  ExtraLightGrey: '#ccc',
};
