export const IMAGES = {
  BabyShower: require('../../assets/image/baby.png'),
  BabyShowerParty: require('../../assets/image/BabyShower.png'),
  CelebAppIcon: require('../../assets/image/celebAppIcon.png'),
  Classic: require('../../assets/image/classic.png'),
  Engagement: require('../../assets/image/Engagement.png'),
  GBbirthday: require('../../assets/image/GBbirthday.png'),
  Golden: require('../../assets/image/golden.png'),
  kid: require('../../assets/image/kid.png'),
  Love: require('../../assets/image/love.png'),
  Marriage: require('../../assets/image/Marriage.png'),
  OD_BTparty: require('../../assets/image/OD-BTparty.png'),
  OD_GBtheme: require('../../assets/image/OD-GBtheme.png'),
  QR: require('../../assets/image/QR.png'),
  RoomDecor: require('../../assets/image/RoomDecor.png'),
  SB1: require('../../assets/image/SB1.png'),
  SB2: require('../../assets/image/SB2.png'),
  SB3: require('../../assets/image/SB3.png'),
  SB4: require('../../assets/image/SB4.png'),
  SB5: require('../../assets/image/SB5.png'),
  SB6: require('../../assets/image/SB6.png'),
  SB7: require('../../assets/image/SB7.png'),
  SB8: require('../../assets/image/SB8.png'),
  Temple: require('../../assets/image/temple.png'),
  Valentine: require('../../assets/image/Valentine.png'),
  Welcome: require('../../assets/image/welcome.png'),
};
